# Auto-generated by wallust.
# Edit ~/.config/wallust/templates/fish-colors.fish instead.

set -g fish_color_normal FDB8DC
set -g fish_color_command C3145A --bold
set -g fish_color_keyword BA29D5 --bold
set -g fish_color_quote 6D0B34
set -g fish_color_redirection F8359C
set -g fish_color_end BA29D5
set -g fish_color_option 6C1677
set -g fish_color_error C3145A --bold
set -g fish_color_operator F8359C
set -g fish_color_param FDB8DC
set -g fish_color_comment AA668A --italics
set -g fish_color_escape BA29D5 --bold
set -g fish_color_match 191318 --background=F8359C
set -g fish_color_autosuggestion AA668A
set -g fish_color_cwd C3145A
set -g fish_color_cwd_root C3145A --bold
set -g fish_color_history_current FDB8DC --bold
set -g fish_color_valid_path 6D0B34 --underline
set -g fish_color_selection FDB8DC --bold --background=3C363B
set -g fish_color_search_match FDB8DC --background=474246
set -g fish_color_cancel C3145A --reverse
set -g fish_color_status C3145A
set -g fish_color_host F8359C
set -g fish_color_host_remote BA29D5
set -g fish_color_setuid 6C1677 --bold
set -g fish_color_user C3145A --bold

set -g fish_pager_color_background --background=191318
set -g fish_pager_color_completion FDB8DC
set -g fish_pager_color_description AA668A --italics
set -g fish_pager_color_prefix F8359C --bold
set -g fish_pager_color_progress AA668A
set -g fish_pager_color_selected_background --background=302B2F
set -g fish_pager_color_selected_completion F392C5 --bold
set -g fish_pager_color_selected_description F8359C
set -g fish_pager_color_selected_prefix BA29D5 --bold
set -g fish_pager_color_secondary_background --background=413A3F
set -g fish_pager_color_secondary_completion FDB8DC
set -g fish_pager_color_secondary_description AA668A
set -g fish_pager_color_secondary_prefix F8359C --bold

set -g pure_color_normal FDB8DC
set -g pure_color_light F392C5
set -g pure_color_dark 413A3F
set -g pure_color_mute AA668A
set -g pure_color_primary C3145A
set -g pure_color_info F8359C
set -g pure_color_success 6D0B34
set -g pure_color_warning 6C1677
set -g pure_color_danger C3145A
