# Auto-generated by wallust.
# Edit ~/.config/wallust/templates/fish-colors.fish instead.

set -g fish_color_normal F6FBF9
set -g fish_color_command 809BAD --bold
set -g fish_color_keyword B4CDE4 --bold
set -g fish_color_quote 526B78
set -g fish_color_redirection E4F3EE
set -g fish_color_end B4CDE4
set -g fish_color_option 7E7985
set -g fish_color_error 809BAD --bold
set -g fish_color_operator E4F3EE
set -g fish_color_param F6FBF9
set -g fish_color_comment A3A8A7 --italics
set -g fish_color_escape B4CDE4 --bold
set -g fish_color_match 0D0409 --background=E4F3EE
set -g fish_color_autosuggestion A3A8A7
set -g fish_color_cwd 809BAD
set -g fish_color_cwd_root 809BAD --bold
set -g fish_color_history_current F6FBF9 --bold
set -g fish_color_valid_path 526B78 --underline
set -g fish_color_selection F6FBF9 --bold --background=312A2E
set -g fish_color_search_match F6FBF9 --background=3D363A
set -g fish_color_cancel 809BAD --reverse
set -g fish_color_status 809BAD
set -g fish_color_host E4F3EE
set -g fish_color_host_remote B4CDE4
set -g fish_color_setuid 7E7985 --bold
set -g fish_color_user 809BAD --bold

set -g fish_pager_color_background --background=0D0409
set -g fish_pager_color_completion F6FBF9
set -g fish_pager_color_description A3A8A7 --italics
set -g fish_pager_color_prefix E4F3EE --bold
set -g fish_pager_color_progress A3A8A7
set -g fish_pager_color_selected_background --background=251D22
set -g fish_pager_color_selected_completion E9F1EE --bold
set -g fish_pager_color_selected_description E4F3EE
set -g fish_pager_color_selected_prefix B4CDE4 --bold
set -g fish_pager_color_secondary_background --background=231D20
set -g fish_pager_color_secondary_completion F6FBF9
set -g fish_pager_color_secondary_description A3A8A7
set -g fish_pager_color_secondary_prefix E4F3EE --bold

set -g pure_color_normal F6FBF9
set -g pure_color_light E9F1EE
set -g pure_color_dark 231D20
set -g pure_color_mute A3A8A7
set -g pure_color_primary 809BAD
set -g pure_color_info E4F3EE
set -g pure_color_success 526B78
set -g pure_color_warning 7E7985
set -g pure_color_danger 809BAD
