# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/13bda0ce-bb0d-4536-9819-c24a52798595";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/13bda0ce-bb0d-4536-9819-c24a52798595";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/13bda0ce-bb0d-4536-9819-c24a52798595";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/13bda0ce-bb0d-4536-9819-c24a52798595";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/13bda0ce-bb0d-4536-9819-c24a52798595";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/13bda0ce-bb0d-4536-9819-c24a52798595";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1E5C-FCF1";
      fsType = "vfat";
      options = [ "umask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/70b5579a-de40-46f2-b5a1-ca49456d85a5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
