general {
    lock_cmd = qs ipc call lockScreen open
    before_sleep_cmd = qs ipc call lockScreen open
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_systemd_inhibit = false
    ignore_dbus_inhibit = false
}

listener {
    timeout = 300
    on-timeout = qs ipc call lockScreen open
}

listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
