# Auto-generated by wallust.
# Edit ~/.config/wallust/templates/fish-colors.fish instead.

set -g fish_color_normal EEDDD5
set -g fish_color_command 86685D --bold
set -g fish_color_keyword 929079 --bold
set -g fish_color_quote 523545
set -g fish_color_redirection CF9E88
set -g fish_color_end 929079
set -g fish_color_option 5A5C42
set -g fish_color_error 86685D --bold
set -g fish_color_operator CF9E88
set -g fish_color_param EEDDD5
set -g fish_color_comment 9C8B83 --italics
set -g fish_color_escape 929079 --bold
set -g fish_color_match 212221 --background=CF9E88
set -g fish_color_autosuggestion 9C8B83
set -g fish_color_cwd 86685D
set -g fish_color_cwd_root 86685D --bold
set -g fish_color_history_current EEDDD5 --bold
set -g fish_color_valid_path 523545 --underline
set -g fish_color_selection EEDDD5 --bold --background=424342
set -g fish_color_search_match EEDDD5 --background=4D4E4D
set -g fish_color_cancel 86685D --reverse
set -g fish_color_status 86685D
set -g fish_color_host CF9E88
set -g fish_color_host_remote 929079
set -g fish_color_setuid 5A5C42 --bold
set -g fish_color_user 86685D --bold

set -g fish_pager_color_background --background=212221
set -g fish_pager_color_completion EEDDD5
set -g fish_pager_color_description 9C8B83 --italics
set -g fish_pager_color_prefix CF9E88 --bold
set -g fish_pager_color_progress 9C8B83
set -g fish_pager_color_selected_background --background=373837
set -g fish_pager_color_selected_completion DFC6BB --bold
set -g fish_pager_color_selected_description CF9E88
set -g fish_pager_color_selected_prefix 929079 --bold
set -g fish_pager_color_secondary_background --background=474847
set -g fish_pager_color_secondary_completion EEDDD5
set -g fish_pager_color_secondary_description 9C8B83
set -g fish_pager_color_secondary_prefix CF9E88 --bold

set -g pure_color_normal EEDDD5
set -g pure_color_light DFC6BB
set -g pure_color_dark 474847
set -g pure_color_mute 9C8B83
set -g pure_color_primary 86685D
set -g pure_color_info CF9E88
set -g pure_color_success 523545
set -g pure_color_warning 5A5C42
set -g pure_color_danger 86685D
