[color]
background = '{{background}}'
foreground = '{{foreground}}'

gradient = 1
gradient_color_1 = '{{color4}}'
gradient_color_2 = '{{color6}}'
gradient_color_3 = '{{color2}}'
gradient_color_4 = '{{color5}}'
gradient_color_5 = '{{color12}}'
gradient_color_6 = '{{color14}}'
gradient_color_7 = '{{color10}}'
gradient_color_8 = '{{color13}}'

horizontal_gradient = 1
horizontal_gradient_color_1 = '{{color4}}'
horizontal_gradient_color_2 = '{{color6}}'
horizontal_gradient_color_3 = '{{color2}}'
horizontal_gradient_color_4 = '{{color5}}'
horizontal_gradient_color_5 = '{{color12}}'
horizontal_gradient_color_6 = '{{color14}}'
horizontal_gradient_color_7 = '{{color10}}'
horizontal_gradient_color_8 = '{{color13}}'

blend_direction = 'up'
