# Auto-generated by wallust.
# Edit ~/.config/wallust/templates/fish-colors.fish instead.

set -g fish_color_normal {{foreground | strip}}
set -g fish_color_command {{color4 | strip}} --bold
set -g fish_color_keyword {{color5 | strip}} --bold
set -g fish_color_quote {{color2 | strip}}
set -g fish_color_redirection {{color6 | strip}}
set -g fish_color_end {{color5 | strip}}
set -g fish_color_option {{color3 | strip}}
set -g fish_color_error {{color4 | strip}} --bold
set -g fish_color_operator {{color6 | strip}}
set -g fish_color_param {{foreground | strip}}
set -g fish_color_comment {{color8 | strip}} --italics
set -g fish_color_escape {{color5 | strip}} --bold
set -g fish_color_match {{background | strip}} --background={{color6 | strip}}
set -g fish_color_autosuggestion {{color8 | strip}}
set -g fish_color_cwd {{color4 | strip}}
set -g fish_color_cwd_root {{color4 | strip}} --bold
set -g fish_color_history_current {{foreground | strip}} --bold
set -g fish_color_valid_path {{color2 | strip}} --underline
set -g fish_color_selection {{foreground | strip}} --bold --background={{background | lighten(0.15) | strip}}
set -g fish_color_search_match {{foreground | strip}} --background={{background | lighten(0.2) | strip}}
set -g fish_color_cancel {{color4 | strip}} --reverse
set -g fish_color_status {{color4 | strip}}
set -g fish_color_host {{color6 | strip}}
set -g fish_color_host_remote {{color5 | strip}}
set -g fish_color_setuid {{color3 | strip}} --bold
set -g fish_color_user {{color4 | strip}} --bold

set -g fish_pager_color_background --background={{background | strip}}
set -g fish_pager_color_completion {{foreground | strip}}
set -g fish_pager_color_description {{color8 | strip}} --italics
set -g fish_pager_color_prefix {{color6 | strip}} --bold
set -g fish_pager_color_progress {{color8 | strip}}
set -g fish_pager_color_selected_background --background={{background | lighten(0.1) | strip}}
set -g fish_pager_color_selected_completion {{color7 | strip}} --bold
set -g fish_pager_color_selected_description {{color6 | strip}}
set -g fish_pager_color_selected_prefix {{color5 | strip}} --bold
set -g fish_pager_color_secondary_background --background={{color0 | strip}}
set -g fish_pager_color_secondary_completion {{foreground | strip}}
set -g fish_pager_color_secondary_description {{color8 | strip}}
set -g fish_pager_color_secondary_prefix {{color6 | strip}} --bold

set -g pure_color_normal {{foreground | strip}}
set -g pure_color_light {{color7 | strip}}
set -g pure_color_dark {{color0 | strip}}
set -g pure_color_mute {{color8 | strip}}
set -g pure_color_primary {{color4 | strip}}
set -g pure_color_info {{color6 | strip}}
set -g pure_color_success {{color2 | strip}}
set -g pure_color_warning {{color3 | strip}}
set -g pure_color_danger {{color4 | strip}}
